
import Navbar from './components/shared/Navbar'
import { AuthContextProvider } from './context/AuthContext'
import { QueryProvider } from './context/QueryProvider'
import './globals.css'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  return (
    <QueryProvider>
      <html lang="en" data-theme="mytheme">
        <body className={inter.className}>

          <AuthContextProvider>
            <Navbar />
            {children}
          </AuthContextProvider>
        </body>
      </html>
    </QueryProvider>

  )
}
